### ISSUE TITLE
cannot load such file -- hpricot

### ISSUE THREAD

**Issue by Chovin** [hacketyhack/hacketyhack#171]
Jumping into Ruby, trying to see where I can help out, and I find this lovely project! Hear great things about it but I haven't been able to experience it first-hand with the site down. Trying to get it installed, I get the following error as well.

using Shoes walkabout 3.3.6
on Windows 7

```rb
Error in <unknown> line 0 | 2018-08-07 10:17:06 +1000
cannot load such file -- hpricot
C:/Program Files (x86)/Shoes/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
C:/Program Files (x86)/Shoes/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
C:/Users/Chovin/Documents/Personal/hacketyhack/app/boot.rb:4:in `<top (required)>'
C:/Program Files (x86)/Shoes/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
C:/Program Files (x86)/Shoes/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
C:/Users/Chovin/Documents/Personal/hacketyhack/app/ui/mainwindow.rb:1:in `<top (required)>'
h-ety-h.rb:5:in `load'
h-ety-h.rb:5:in `<main>'
C:/Program Files (x86)/Shoes/lib/shoes.rb:351:in `eval'
C:/Program Files (x86)/Shoes/lib/shoes.rb:351:in `visit'
eval:1:in `<main>'
```

Is this related to #161 ?
I noticed the last comment was in 2013. Surely this has been used after that. How have you guys gotten it to work?

I will update if I can get it working.

**Comment by PragTob** [comment]
:wave: 

Thanks for checking in. Sorry, but hacketyhack hasn't seen work in a LONG time... focus shifted more towads shoes and also maybe not as much. It looks like you might just be missing the hpricot gem in your shoes installation... in Shoes3 I believe it's something like `Shoes.setup do gem "hpricot" end`.

@ccoupe

**Comment by ccoupe** [comment]
Hi @Chovin , last I looked, hackeyhack would run circa 2015 with Shoes 3.2 but only if hh was in a shy container or loose files. Those can be found [here](https://shoes.mvmanila.com/public/hh)  As @PragTob noted we've moved to Nokogiri instead of Hpricot for XML parsing. Getting a binary hpricot gem for Windows 7 would be a challenge. Better to get HH working with nokogiri  by changing the `requires` in HH and whatever calls it. samples/expert/funnies.rb might have a clue left over in it - it used to use hpricot.
